/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void Forward_click1(GButton source, GEvent event) { //_CODE_:Forward:623351:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  send('w');                                                    //Sends the char to the xBee Module
} //_CODE_:Forward:623351:

public void Right_click1(GButton source, GEvent event) { //_CODE_:Right:637373:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  send('d');                                                        //Sends the char to the xBee Module
} //_CODE_:Right:637373:

public void Back_click1(GButton source, GEvent event) { //_CODE_:Back:885457:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  send('s');                                                       //Sends the char to the xBee Module
} //_CODE_:Back:885457:

public void Left_click1(GButton source, GEvent event) { //_CODE_:Left:588872:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  send('a');                                                        //Sends the char to the xBee Module
} //_CODE_:Left:588872:

public void Stop_click1(GButton source, GEvent event) { //_CODE_:Stop:768888:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  send('c');                                                        //Sends the char to the xBee Module
} //_CODE_:Stop:768888:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:ZumoInput:698218:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ZumoInput:698218:

public void Send_click1(GButton source, GEvent event) { //_CODE_:Send:922618:
  println("Send - GButton >> GEvent." + event + " @ " + millis());
  
  String line = ZumoInput.getText();                                        //Gets the text from the ZumoInput textbox
  char input = line.charAt(0);                                              //Gets the first char in the String...
  ZumoInput.setText("");                                                    //Resets the ZumoInput textbox to be empty
  send(input);                                                              //Sends the char to the xBee Module
  
} //_CODE_:Send:922618:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:523755:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:523755:

public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:History:247336:
  println("textarea2 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:History:247336:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Zumo control");
  Forward = new GButton(this, 70, 10, 50, 50);
  Forward.setText("W");
  Forward.addEventHandler(this, "Forward_click1");
  Right = new GButton(this, 130, 70, 50, 50);
  Right.setText("D");
  Right.addEventHandler(this, "Right_click1");
  Back = new GButton(this, 70, 70, 50, 50);
  Back.setText("S");
  Back.addEventHandler(this, "Back_click1");
  Left = new GButton(this, 10, 70, 50, 50);
  Left.setText("A");
  Left.addEventHandler(this, "Left_click1");
  Stop = new GButton(this, 200, 10, 70, 50);
  Stop.setText("Stop");
  Stop.addEventHandler(this, "Stop_click1");
  ZumoInput = new GTextField(this, 10, 150, 190, 20, G4P.SCROLLBARS_NONE);
  ZumoInput.setOpaque(true);
  ZumoInput.addEventHandler(this, "textfield1_change1");
  Send = new GButton(this, 200, 150, 70, 20);
  Send.setText("Send");
  Send.addEventHandler(this, "Send_click1");
  textarea1 = new GTextArea(this, 10, 200, 130, 100, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  History = new GTextArea(this, 150, 200, 130, 100, G4P.SCROLLBARS_NONE);
  History.setOpaque(true);
  History.addEventHandler(this, "textarea2_change1");
  label1 = new GLabel(this, 10, 130, 80, 20);
  label1.setText("Zumo Input");
  label1.setOpaque(false);
  label2 = new GLabel(this, 150, 180, 80, 20);
  label2.setText("Input history");
  label2.setOpaque(false);
  label3 = new GLabel(this, 10, 180, 80, 20);
  label3.setText("Zumo Output");
  label3.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton Forward; 
GButton Right; 
GButton Back; 
GButton Left; 
GButton Stop; 
GTextField ZumoInput; 
GButton Send; 
GTextArea textarea1; 
GTextArea History; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
